name: Test
on:
  pull_request:
    branches: [next]
jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v2
      - name: Install dependencies
        id: cache-keys
        uses: ./.github/composite-actions/install-dependencies
    outputs:
      root_cache_key: ${{ steps.cache-keys.outputs.root_cache_key }}

  test-jest:
    name: Test jest
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v2
      - name: Install dependencies
        id: cache-keys
        uses: ./.github/composite-actions/install-dependencies
      - name: run unit test
        run: |
          npm run test

  test-playwright:
    name: Test playwright
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v2
      - name: Install dependencies
        id: cache-keys
        uses: ./.github/composite-actions/install-dependencies
      - name: Install playwright dependencies
        run: |
          npx playwright install --with-deps
      - name: Build storybook
        run: |
          npx lerna run --scope @toast-ui/calendar storybook:build
      - name: Run E2E test
        run: |
          npm run test:playwright
