name: Test
on:
  pull_request:
    branches: [next]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./apps/calendar
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul
      - name: npm install(jest)
        run: |
          npm install
      - name: build libs/date
        run: |
          npm run setup:date
      - name: npm install(toast.ui-calendar)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm install
      - name: test
        run: |
          npm run test
