name: Test
on:
  pull_request:
    branches: [next]
  workflow_call:
jobs:
  lint:
    name: Lint & Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/composite-actions/install-dependencies
      - name: Lint & Type Checking
        run: |
          # This should check all packages when other packages are ready.
          npm run validate -w "@toast-ui/calendar" 

  test-jest:
    name: Test jest
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/composite-actions/install-dependencies
      - name: run unit test
        run: |
          npm run test

  test-playwright:
    name: Test playwright
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/composite-actions/install-dependencies
      - name: Install playwright dependencies
        run: |
          npx playwright install --with-deps
      - name: Build storybook
        run: |
          npm run storybook:build -w "@toast-ui/calendar"
      - name: Run E2E test
        run: |
          npm run test:playwright
